services:
  web:
    build: .
    restart: always
    command: gunicorn SolarStationServer.wsgi:application --bind 0.0.0.0:5001 --workers 3
    ports:
      - "5001:5001"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*
