name: Pull Request Check

on:
  pull_request:
    branches:
      - master

env:
  USE_SQLITE: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check code style with Flake8
        run: flake8
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests with coverage
        run: |
          coverage run --source='.' manage.py test
      - name: Generate coverage report
        run: coverage report --fail-under=90
